"""Evaluate deterministic customer simulation outputs against Track D hypotheses."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

# Ensure repository root is on import path when executed as a script.
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.simulation.customer_hypotheses import load_customer_hypotheses
from src.simulation.customer_hypothesis_evaluator import evaluate_customer_hypotheses
from src.utils.config import settings
from src.utils.logging import get_logger, setup_logging

logger = get_logger(__name__)


def _load_summary(path: str) -> Dict[str, Any]:
    resolved_path = Path(path)
    if not resolved_path.exists():
        raise FileNotFoundError(f"Scenario summary file not found: {resolved_path}")

    with resolved_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if not isinstance(payload, dict):
        raise ValueError("Scenario summary must be a JSON object.")
    if "scenarios" not in payload:
        raise ValueError("Scenario summary is missing required key: 'scenarios'.")
    return payload


def _print_report(report: Dict[str, Any], verbose: int) -> None:
    print("\n" + "=" * 72)
    print("TRACK D HYPOTHESIS EVALUATION")
    print("=" * 72)
    print(
        f"Overall status: {report['overall_status'].upper()} "
        f"(pass={report['counts']['pass']}, warn={report['counts']['warn']}, fail={report['counts']['fail']})"
    )

    if report["determinism_failures"]:
        print("Determinism failures:", ", ".join(report["determinism_failures"]))

    for result in report["results"]:
        observed = (
            "n/a"
            if result["observed_delta"] is None
            else f"{float(result['observed_delta']):+.4f}"
        )
        print(
            f"- {result['id']} [{result['status'].upper()}] "
            f"scenario={result['scenario']} metric={result['metric']} "
            f"observed={observed}"
        )

        if verbose >= 2:
            for check in result["checks"]:
                print(
                    f"    * {check['check']} [{check['status'].upper()}] {check['message']}"
                )

    if report["notes"]:
        print("Notes:")
        for note in report["notes"]:
            print(f"- {note}")

    print("=" * 72 + "\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate customer scenario summary against Track D hypotheses "
            "and produce pass/warn/fail verdicts."
        )
    )
    parser.add_argument(
        "--summary-path",
        type=str,
        default="data/memory/customer_matrix_summary.json",
        help=(
            "Path to JSON summary generated by scripts/run_customer_simulation.py "
            "(default: data/memory/customer_matrix_summary.json)."
        ),
    )
    parser.add_argument(
        "--hypotheses-path",
        type=str,
        default=settings.customer_hypotheses_path,
        help="Path to hypothesis file (default from CUSTOMER_HYPOTHESES_PATH).",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=None,
        help="Optional file path to write full evaluation report as JSON.",
    )
    parser.add_argument(
        "--verbose",
        type=int,
        choices=[0, 1, 2],
        default=1,
        help="Output verbosity: 0=minimal, 1=default, 2=detailed checks.",
    )
    parser.add_argument(
        "--allow-warn",
        action="store_true",
        help="Return success exit code when overall status is WARN.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    setup_logging(settings.log_level)

    logger.info("Loading scenario summary from %s", args.summary_path)
    summary = _load_summary(args.summary_path)

    logger.info("Loading hypotheses from %s", args.hypotheses_path)
    hypotheses = load_customer_hypotheses(hypotheses_path=args.hypotheses_path)

    report = evaluate_customer_hypotheses(summary, hypotheses)

    if args.verbose > 0:
        _print_report(report, verbose=args.verbose)

    if args.json_out:
        output_path = Path(args.json_out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"Wrote JSON report: {output_path}")

    status = report["overall_status"]
    if status == "pass":
        return 0
    if status == "warn" and args.allow_warn:
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
